server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React-style routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proper MIME for JS
    types {
        text/javascript js;
    }
}
